// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"example/test-golang/config"
	"example/test-golang/controller"
	"example/test-golang/http"
	"example/test-golang/repository"
	"example/test-golang/service"
)

// Injectors from di.go:

func InitializeApplication(ctx context.Context) (*Application, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	userRepository := repository.ProvideUserRepository()
	userService := service.ProvideUserService(userRepository)
	userController := controller.ProvideUserController(userService)
	server := http.ProvideServer(configConfig, userController)
	application := &Application{
		Srv: server,
	}
	return application, nil
}
